# Generated by Django 6.0.6 on 2026-06-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variations',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
