# Generated by Django 6.0.6 on 2026-06-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('store', '0004_alter_variations_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='carditem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variations'),
        ),
    ]
